apiVersion: apps/v1beta2
kind: Deployment
metadata:
  annotations:
    field.cattle.io/creatorId: ""
    field.cattle.io/publicEndpoints: '[{"port":32080,"protocol":"TCP","serviceName":"charity:charity-frontend-nodeport","allNodes":true}]'
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-charity-charity-frontend
  name: charity-frontend
  namespace: charity
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-charity-charity-frontend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        field.cattle.io/ports: '[[{"containerPort":80,"dnsName":"charity-frontend-nodeport","kind":"NodePort","name":"80tcp320801","protocol":"TCP","sourcePort":32080}]]'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-charity-charity-frontend
    spec:
      containers:
      - image: repo.alphacario.com:8089/charity-frontend
        imagePullPolicy: Always
        name: charity-frontend
        ports:
        - containerPort: 80
          name: 80tcp320801
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          procMount: Default
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: nexus-lm
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      